# Generated by Django 5.1.3 on 2025-02-18 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='a_image',
        ),
    ]
