# Generated by Django 5.1.3 on 2025-01-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='category/')),
            ],
        ),
        migrations.AlterField(
            model_name='tbl_admin',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
