# Generated by Django 5.1.3 on 2025-01-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_category_alter_tbl_admin_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
        migrations.AlterField(
            model_name='tbl_admin',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
