# Generated by Django 5.1.3 on 2025-03-01 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_remove_employee_a_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_category',
            name='price',
        ),
    ]
