# Generated by Django 5.1.7 on 2025-03-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_wastethreshold_quotation_wastethreshold_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastethreshold',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('collected', 'Collected')], default='pending', max_length=20),
        ),
    ]
