# Generated by Django 5.1.3 on 2025-01-31 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_tbl_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_admin',
            old_name='password',
            new_name='pswd',
        ),
    ]
