# Generated by Django 5.1.3 on 2025-02-21 09:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0002_remove_employee_a_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('pswd', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=255)),
                ('phone', models.CharField(max_length=100)),
                ('utype', models.CharField(default='user', max_length=100)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.ward')),
            ],
        ),
        migrations.CreateModel(
            name='WasteSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('complete', 'Complete'), ('incomplete', 'Incomplete')], default=' pending', max_length=20)),
                ('categories', models.TextField()),
                ('category_prices', models.TextField()),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.tbl_register')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_option', models.CharField(choices=[('cash', 'Cash'), ('card_payment', 'Card Payment')], max_length=20)),
                ('status', models.CharField(choices=[('cash', 'Cash'), ('card_payment', 'Card Payment')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name_of_card', models.CharField(blank=True, max_length=255, null=True)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('expiry_date', models.CharField(blank=True, max_length=5, null=True)),
                ('cvv', models.CharField(blank=True, max_length=3, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.tbl_register')),
                ('waste_submission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.wastesubmission')),
            ],
        ),
    ]
