# Generated by Django 5.1.3 on 2025-02-17 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('pswd', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=255)),
                ('phone', models.CharField(max_length=100)),
                ('utype', models.CharField(default='user', max_length=100)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.ward')),
            ],
        ),
        migrations.CreateModel(
            name='WasteSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('incomplete', 'Incomplete')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.tbl_register')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_option', models.CharField(choices=[('cash_on_delivery', 'Cash on Delivery'), ('card_payment', 'Card Payment')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('expiry_date', models.CharField(blank=True, max_length=5, null=True)),
                ('cvv', models.CharField(blank=True, max_length=3, null=True)),
                ('cardholder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.tbl_register')),
                ('waste_submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userapp.wastesubmission')),
            ],
        ),
        migrations.CreateModel(
            name='WasteSubmissionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilogram', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_category')),
                ('waste_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='userapp.wastesubmission')),
            ],
        ),
    ]
