# Generated by Django 5.1.7 on 2025-03-24 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_tbl_register_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.MinLengthValidator(16, message='Card number must be exactly 16 digits.'), django.core.validators.RegexValidator('^\\d{16}$', message='Card number must contain only digits.')]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cvv',
            field=models.CharField(blank=True, max_length=3, null=True, validators=[django.core.validators.MinLengthValidator(3, message='CVV must be exactly 3 digits.'), django.core.validators.RegexValidator('^\\d{3}$', message='CVV must contain only digits.')]),
        ),
    ]
