# Generated by Django 5.1.3 on 2025-02-17 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_payment_payment_option'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
