# Generated by Django 5.1.3 on 2025-02-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cash', 'Cash'), ('card_payment', 'Card Payment')], default='pending', max_length=20),
        ),
    ]
