# Generated by Django 5.1.3 on 2025-02-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastesubmission',
            name='kilograms',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wastesubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('complete', 'Complete'), ('incomplete', 'Incomplete')], default='pending', max_length=20),
        ),
    ]
