# Generated by Django 5.1.3 on 2025-02-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_wastesubmission_kilograms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_register',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
