# Generated by Django 5.1.3 on 2025-02-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_option',
            field=models.CharField(choices=[('cash', 'Cash'), ('card_payment', 'Card Payment')], max_length=20),
        ),
    ]
