# Generated by Django 5.1.3 on 2025-02-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_tbl_register_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_register',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_register',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
