# Generated by Django 5.1.3 on 2025-02-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_tbl_register_latitude_tbl_register_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_register',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_register',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
