# Generated by Django 5.1.3 on 2025-02-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_alter_payment_payment_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastesubmission',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
