# Generated by Django 5.1.3 on 2025-02-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_wastesubmission_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastesubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('complete', 'Complete'), ('incomplete', 'Incomplete')], default='pending', max_length=20),
        ),
    ]
