# Generated by Django 5.1.3 on 2025-02-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_alter_wastesubmission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastesubmissiondetail',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
