# Generated by Django 5.1.3 on 2025-02-25 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_alter_tbl_register_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_register',
            name='location',
        ),
    ]
