# Generated by Django 5.1.3 on 2025-02-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_wastesubmissiondetail_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='cardholder_name',
        ),
        migrations.AddField(
            model_name='payment',
            name='name_of_card',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
