# Generated by Django 5.1.3 on 2025-02-18 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_remove_payment_cardholder_name_payment_name_of_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_option',
            field=models.CharField(choices=[('cash', 'Cash'), ('card_payment', 'Card Payment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='waste_submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.wastesubmission'),
        ),
    ]
