# Generated by Django 5.1.3 on 2025-03-01 07:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_remove_tbl_register_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastesubmission',
            name='category_prices',
        ),
        migrations.RemoveField(
            model_name='wastesubmission',
            name='kilograms',
        ),
        migrations.AlterField(
            model_name='wastesubmission',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10),
        ),
    ]
