# Generated by Django 5.1.3 on 2025-03-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_remove_wastesubmission_category_prices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastesubmission',
            name='kilo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
