# Generated by Django 5.1.3 on 2025-02-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_alter_payment_payment_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastesubmission',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
