# Generated by Django 5.1.3 on 2025-03-04 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_wastesubmission_kilo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastesubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('incomplete', 'Incomplete')], default='pending', max_length=20),
        ),
    ]
