# Generated by Django 5.1.3 on 2025-03-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_alter_wastesubmission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastesubmission',
            name='cash_status',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('not_paid', 'Not Paid')], default='not_paid', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='wastesubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('incompleted', 'Incompleted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
