# Generated by Django 5.1.3 on 2025-03-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_wastesubmission_cash_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastesubmission',
            name='cash_status',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('not_paid', 'Not Paid')], max_length=10, null=True),
        ),
    ]
