# Generated by Django 5.1.3 on 2025-03-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0017_alter_wastesubmission_cash_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastesubmission',
            name='cash_status',
        ),
        migrations.AlterField(
            model_name='wastesubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('incompleted', 'Incompleted')], default='pending', max_length=20),
        ),
    ]
