# Generated by Django 5.1.3 on 2025-03-05 06:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0018_remove_wastesubmission_cash_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastesubmission',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
