# Generated by Django 5.1.3 on 2025-03-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0021_rename_price_payment_total_price_payment_cash_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastesubmission',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
