# Generated by Django 5.1.3 on 2025-03-05 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0022_wastesubmission_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='description',
        ),
    ]
